# Generated by Django 4.2.6 on 2023-10-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ytd_web_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadable",
            name="expiration_period",
            field=models.IntegerField(default=5),
        ),
    ]
